### ISSUE TITLE
Weekly downloads: don't include partial weeks

### ISSUE THREAD

**Issue by hugovk** [psincraian/pepy#633]
The monthly emails contain a "Total downloads by day" chart:

![image](https://github.com/psincraian/pepy/assets/1324225/22b08cf5-3562-4a51-bb3a-0e261f0bec73)

I guess that huge dip at the end is because an incomplete week is used? For example, the last week of February was only four days (26-29).

Please can you exclude the final partial week? The chart is "Weekly downloads" not "Monthly downloads", so please only include full weeks. It's always surprising to open the email and wonder why the downloads have plummeted and what's gone wrong!

I think by not starting the axis at zero makes it look even more drastic.

And should "Total downloads by day" be "Total downloads by week"?

**Comment by psincraian** [comment]
That makes total sense, I will remove the incomplete week. Thanks @hugovk :D

**Comment by psincraian** [comment]
Should be fixed by next report :)

**Comment by hugovk** [comment]
Thank you, this is looking better for end of the chart, but the April chart still shows a big dip at the start:

<img width="577" alt="image" src="https://github.com/psincraian/pepy/assets/1324225/924b8289-e53f-4012-809b-a119abd6853d">

Please could you remove any incomplete starting weeks as well?

**Comment by hugovk** [comment]
Hmm, today's shows a dip at the end:

![Screenshot_20240601_131728_Gmail](https://github.com/psincraian/pepy/assets/1324225/67a96e57-dfea-4e8c-87d5-000537d814b2)

Please could you re-open this? Thanks!

**Comment by psincraian** [comment]
Hey @hugovk 

Sorry but it's not really related. The problem is that the last week of May there was a bug on the data and downloads were way below than normal.

The bug is fixed, but I wasn't on time to fix the old data in the past

**Comment by hugovk** [comment]
OK, good to hear, and thanks for pepy!
