### ISSUE TITLE
Downloads show wrong numbers since May 19

### ISSUE THREAD

**Issue by WenjieDu** [psincraian/pepy#667]
Since May 19, downloads have dropped to very small numbers, e.g. `numpy` shown in the below screenshot

<img width="1034" alt="image" src="https://github.com/psincraian/pepy/assets/17807970/d00a0326-0f79-455f-95f0-1cf76a8c44f3">

**Comment by fcakyon** [comment]
Yes, there seems to be an issue with the download stats for the past few days. We have observed this in our package statistics.

**Comment by psincraian** [comment]
I need to check what happened. I will do it on Monday as now I'm on holidays

**Comment by PythonSJL** [comment]
![data](https://github.com/psincraian/pepy/assets/162294038/a5dc561a-81b8-4386-80ae-9eb0df487d09)
I used to wonder why the PyPyNum 1.9.0 download I updated yesterday only had a dozen or so downloads, but now I finally know : )

**Comment by SWHL** [comment]
I met the same problem with `rapidocr_onnxruntime` package as like following ([link](https://www.pepy.tech/projects/rapidocr_onnxruntime)):
<img width="1151" alt="image" src="https://github.com/psincraian/pepy/assets/28639377/3c74ded0-de10-4c47-ab8c-28435dadfb52">

**Comment by psincraian** [comment]
Now it's working fine again. 

I'm still pending on update the older data. I expect to have it fixed by this week

**Comment by WenjieDu** [comment]
Thanks @psincraian. I'm going to close this issue.

**Comment by YarShev** [comment]
> Now it's working fine again.
> 
> I'm still pending on update the older data. I expect to have it fixed by this week

@psincraian, is there an update on this? It seems the older data is still shown incorrectly.

**Comment by WenjieDu** [comment]
> > Now it's working fine again.
> > I'm still pending on update the older data. I expect to have it fixed by this week
> 
> @psincraian, is there an update on this? It seems the older data is still shown incorrectly.

@YarShev is right. I'm reopening this issue for discussion.

**Comment by psincraian** [comment]
Hey,

Sorry for the delay. Slowly the downloads are fixed for those days. You can keep the issue open until everything is fixed

**Comment by YarShev** [comment]
What I see is the period of May 23 - 26 is still shown incorrectly. We are almost there.

**Comment by WenjieDu** [comment]
> What I see is the period of May 23 - 26 is still shown incorrectly. We are almost there.

But our library PyPOTS shows incorrect downloads from May 21 to 26 https://www.pepy.tech/projects/pypots

**Comment by YarShev** [comment]
@WenjieDu, you should probably reload the page (maybe clear the cache). Now I see the period of May 25 - 26, which is shown incorrectly.

**Comment by dcajasn** [comment]
It seems that the error is back. I attached numpy link and results. https://www.pepy.tech/projects/Numpy
![IMG_0559](https://github.com/psincraian/pepy/assets/61527316/b3a3df67-575c-42bf-9e87-67eb202c7b58)

**Comment by hugovk** [comment]
Please see https://github.com/psincraian/pepy/issues/679

**Comment by psincraian** [comment]
All wrong dates were backfilled ☺️

**Comment by YarShev** [comment]
Thanks folks!
